### ISSUE TITLE
[UX] Can not return the filter

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/pim-app#227] opened 2023-02-22 10:00 UTC
1. Launch app at local
2.  Login and go to product management
3. Filter with published. The page display the result
4. User want to remove select All in filter
Actual outcome:
The user can not select All in filter once the published has been selected. Note: please do check for other filter
![image](https://user-images.githubusercontent.com/30283123/220586739-882e3cfb-e107-4556-b472-d05a9c0e1eca.png)

**Comment by lklong709** [comment] 2023-03-01 07:17
@thaoredweb close it, it not a bug

**Closed** 2023-06-19 06:58 UTC
