### ISSUE TITLE
Display message when filtering

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/pim-app#226] opened 2023-02-22 09:54 UTC
1. Launch the app at local
2. Filter with unpublish

Actual output:
Show the error message. Check for all status right now
![image](https://user-images.githubusercontent.com/30283123/220585388-1fcebd4b-94ac-4619-98b6-3dbeecc4cac9.png)

**Comment by lklong709** [comment] 2023-03-01 07:17
@thaoredweb Close it, it not a bug

**Closed** 2023-03-01 07:19 UTC
